### ISSUE TITLE
会支持Arm64平台吗

### ISSUE THREAD

**Issue by asforest** [tencentyun/coscli#21]
coscli会支持arm64平台吗，因为一些原因需要在arm开发板上使用对象存储。但是发现只有x86的三个平台的版本，未来会增加arm64平台的可执行文件吗？

**Comment by dforel** [comment]
这个为什么关闭了，意思是已经支持，还是不打算支持。

**Comment by asforest** [comment]
> 这个为什么关闭了，意思是已经支持，还是不打算支持。

arm64版本的已经自己编译解决了，好在编译也挺简单。官方版本得等到猴年马月去。如果需要ARM64版的话，只能自己下载GO亲自编译。
