### ISSUE TITLE
Log would fail it I put coscli to system path

### ISSUE THREAD

**Issue by ma-joel** [tencentyun/coscli#24]
For instance if i copy `coscli` to `/usr/local/bin/coscli` and run by calling `coscli`, the log would fail as no permissions. output is like
```
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/bin/coscli.log [%!s(*strftime.verbatimw=&{/usr/local/bin/coscli.log})]}: open /usr/local/bin/coscli.log: permission denied
```

**Comment by lewzylu** [comment]
Maybe you need to use the root account or adjust the permissions of the current user
