### ISSUE TITLE
cp命令使用相对路径输出日志错误。

### ISSUE THREAD

**Issue by jackblue200043** [tencentyun/coscli#27]
![image](https://user-images.githubusercontent.com/55248478/202354913-e8dbc773-4dc0-4fe2-b235-af1e3146bedf.png)

命令`Upload /root/bin/test/test2.file => cos://backup/test/test2.file`。
日志中上传的路径应该是`/root/bin/test/test.file`，而不是`/root/bin/./test/test.file`。

**Comment by lewzylu** [comment]
感谢建议，这边会优化

**Comment by willppan** [comment]
新版本已优化
