### ISSUE TITLE
能否隐藏输出信息里的bucket

### ISSUE THREAD

**Issue by BlueHtml** [tencentyun/coscli#32]
上传文件时，输出信息里有`bucket`的信息，例如：`INFO[2023-02-09 07:42:51] Upload /home/runner/work/Note/Note/note/today.txt => cos://bucket1/note/today.txt`。
当在公开环境中使用时（例如github action），会暴露`bucket`的信息。而如果存储桶开启了**外网访问/公有读**，可能会被有心人利用，拼接URL来刷流量，导致高额的流量费用。
能否设置个`开关项`/`参数`，开启后就在输出信息里**隐藏**掉`bucket`？（可以设置为默认是关闭的，会显示`bucket`）

**Comment by willppan** [comment]
您好，可以将输出打印至指定文件来避免
