### ISSUE TITLE
mac M1 支持

### ISSUE THREAD

**Issue by yuyicai** [tencentyun/coscli#37]
虽然 x86 的 coscli 可以在 M1 运行，但是希望能多编译一个 arm 版本
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/13033733/232024845-134a63ac-5988-46dc-8639-7b2301a61690.png">

**Comment by MartinGao** [comment]
+1  希望可以编译arm版本

**Comment by Jamlee** [comment]
+1 希望可以编译arm版本

**Comment by yuyicai** [comment]
等不及了，我用 Github action 自动构建发布了一波，包含各个平台的 x86 和 arm64 构建产物
https://github.com/yuyicai/coscli/releases/tag/v0.13.0-beta2
