### ISSUE TITLE
需求: 能支持 arm64 下面的 Linux 平台的命令行么?

### ISSUE THREAD

**Issue by Sn0rt** [tencentyun/coscli#40]

**Comment by tianyu-sz** [comment]
同问

**Comment by yuyicai** [comment]
官方有点佛系，我这里编译了全套平台的
https://github.com/yuyicai/coscli/releases/tag/v0.13.0-beta2
<img width="1209" alt="image" src="https://github.com/tencentyun/coscli/assets/13033733/ca026f46-4d51-4d23-94bb-cdaccdaf7be7">

**Comment by willppan** [comment]
您好，目前新版本已支持
