### ISSUE TITLE
du统计大文件夹内存占用过高

### ISSUE THREAD

**Issue by ycq0125** [tencentyun/coscli#50]
<img width="1634" alt="image" src="https://github.com/tencentyun/coscli/assets/49603999/83001bc7-d783-4244-ba72-12769a855b85">

**Comment by ycq0125** [comment]
@willppan

**Comment by willppan** [comment]
您好，du命令会拉取指定cos路径下的所有对象及子目录下的对象，占用高不可避免，在新版本中已经对性能做了优化，可升级至最新版本使用
