### ISSUE TITLE
Where can I get the release of arm architecture?

### ISSUE THREAD

**Issue by zclllyybb** [tencentyun/coscli#52]
When I follow the doc to download the Linux release, I got x86-64 version:
```bash
> file coscli
coscli: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

can I build it from source for the correct architecture or download it for arm?

**Comment by willppan** [comment]
Hello, the latest version of coscli now supports the Linux ARM architecture. You can download the latest version from the official website.
