### ISSUE TITLE
当多层级文件目录下遍布了许多零散小文件时，上传速度过慢

### ISSUE THREAD

**Issue by hbpp** [tencentyun/coscli#54]
coscli团队你们好：

我知道如果对现有coscli程序中添加多线程批量上传功能会有很大的工作量。但如果我有一个目录，下面有上万个小文件，分布在多个层级目录下。现在的速度很慢很慢。虽然现在对于单个大文件有多线程分块上传功能。但多线程批量同时上传小文件同样也需要。

所以请着手安排一下。亚马逊的aws工具就有这个功能。

感谢！

**Comment by willppan** [comment]
目前多文件不支持批量，这里正在做优化



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月22日(周五) 下午5:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tencentyun/coscli] 当多层级文件目录下遍布了许多零散小文件时，上传速度过慢 (Issue #54)




 
coscli团队你们好：
 
我知道如果对现有coscli程序中添加多线程批量上传功能会有很大的工作量。但如果我有一个目录，下面有上万个小文件，分布在多个层级目录下。现在的速度很慢很慢。虽然现在对于单个大文件有多线程分块上传功能。但多线程批量同时上传小文件同样也需要。
 
所以请着手安排一下。亚马逊的aws工具就有这个功能。
 
感谢！

**Comment by willppan** [comment]
您好，目前新版本已支持并发上传下载，可通过指定并发数来提升传输效率
