### ISSUE TITLE
不支持下载目录？

### ISSUE THREAD

**Issue by ronyman** [tencentyun/coscli#6]

**Comment by ChloroplastYu** [comment]
支持下载目录，若有问题请提供截图

**Comment by ronyman** [comment]
cos上a目录结构如下：

-a

--a1

---.ttt.log

---file2

---file3

---dir1

----file11

----file12

---dir2

----file21

----file22

--file1
执行下面的命令

$ ./coscli cp  cos://files/a/ /home/test/dl_cos/ -r
输出的提示如下：

stat /home/test/dl_cos/a1/.ttt.log: no such file or directory

**Comment by ChloroplastYu** [comment]
0.10.2-beta已修复此问题
