### ISSUE TITLE
是否可以考虑发布官方docker镜像？

### ISSUE THREAD

**Issue by BoringCat** [tencentyun/coscli#69]
我们团队正在将上传文件的操作集成到CI中，CI执行环境是k8s，但只能找到[coscmd的官方docker镜像][1]，找不到coscli的官方docker镜像。

或许可以像 coscmd 那样打个镜像，推送到 dockerhub？  
这样能简化很多配置，也不需要手动跟随版本打镜像

[1]: https://hub.docker.com/r/tencentcom/tencentyun-coscmd

**Comment by willppan** [comment]
您好，感谢建议，后续会支持
