### ISSUE TITLE
v0.10.1-beta 版本不能从 cos 上拷贝目录，提示 stat : no such file or directory

### ISSUE THREAD

**Issue by ccoder64** [tencentyun/coscli#7]

**Comment by ChloroplastYu** [comment]
您好，请问是否能够提供错误信息与相应截图呢？

**Comment by ccoder64** [comment]
@ChloroplastYu 
![image](https://user-images.githubusercontent.com/10257116/146627765-ddcdf76f-1651-4f8d-ba0b-1d0d61ca9b0d.png)

**Comment by ChloroplastYu** [comment]
0.10.2-beta已经修复此问题
