### ISSUE TITLE
cp 命令能否支持修改存量文件的存储类型？

### ISSUE THREAD

**Issue by A-Circle-Zhang** [tencentyun/coscli#81]
cp 命令的 `--storage-class` 选项只支持上传文件的时候设置，如果在 COS 内复制则会报错 ` --storage-class can only use in upload` 。

但我需要通过 coscli 工具，批量修改存量文件的存储类型。

https://github.com/tencentyun/coscli/blob/fa3fdd6ae900d09ddcc2a298048159c428ca742d/cmd/cp.go#L326

我看到源代码里面 `cosCopy` 函数，似乎是支持 `storageClass` 的，但命令行层面进行了限制，不知道为什么，能否允许 COS 内复制时修改存储类型呢？

**Comment by willppan** [comment]
感谢您的建议，这个功能下个版本会支持。
